### ISSUE TITLE
App does not open in flatpak

### ISSUE THREAD

**Issue by krouma** [Nitrokey/nitrokey-app2#219]
Version: 2.2.1
When a Nitrokey 3A is already connected, the app crashes right away. When I run it from a terminal, I get the following error:
```
Traceback (most recent call last):
  File "/app/bin/nitrokeyapp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/nitrokeyapp/__main__.py", line 34, in main
    window = GUI(app, log_file)
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 182, in __init__
    self.init_gui()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 334, in init_gui
    self.detect_added_devices()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 233, in detect_added_devices
    self.toggle_update_btn()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 211, in toggle_update_btn
    self.overview_tab.set_update_enabled(device_count == 1)
  File "/app/lib/python3.11/site-packages/nitrokeyapp/overview_tab.py", line 120, in set_update_enabled
    self.disable_update_nrf()
  File "/app/lib/python3.11/site-packages/nitrokeyapp/overview_tab.py", line 51, in disable_update_nrf
    if IS_FLATHUB and self.data.status.variant.name == "NRF52":
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
QThread: Destroyed while thread is still running
```
If I don't have a key inserted, the app opens. It then shows the same error when I insert the key.
It looks like a problem in the code, so I created the issue here and not in the flathub repo.

**Comment by krouma** [comment]
My setup

- Nitrokey 3A NFC, my order also contains code [NK3AN]
- Fedora 39, kernel `6.7.5-200.fc39.x86_64`

I ordered the key when it was released in October 2022 so it probably has a very old firmware. I'll try to update it with `nitropy`.

**Comment by krouma** [comment]
The firmware version was 1.2.2, after update to 1.6.0, the app works.

**Comment by daringer** [comment]
good to hear, ok, looks like we need some safe-guards for older firmware versions here, thank you for finding this!

**Comment by daringer** [comment]
created an issue to fix this issue: https://github.com/Nitrokey/nitrokey-app2/issues/220 closing this issue in favor of that one.
